site:
  title: Magnolia CMS Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: http://localhost:9096/
  start_page: home::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: home
  - url: https://git.magnolia-cms.com/scm/~amansell/magnolia-docs.git
    branches:
      - master
      
ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"

# Global asciidoc attributes here
asciidoc:
  attributes:
    magnolia-help-desk: HELPDESK
    magnolia-url: www.magnolia-cms.com
    experimental:
    
