= Magnolia Documentation
:page-layout: home
:page-role: tiles
:!sectids:

= Magnolia Documentation
++++
<div class="card-row">
++++

[.column]
====== {empty}
[.content]
Find the documentation, samples, and references to help you use Magnolia and build applications. 

[.column]
====== {empty}
[.media-left]
image::get-the-agility-of-sql-and-the-flexibility-of-json.svg[,300]

++++
</div>
++++

== Get Started
++++
<div class="card-row two-column-row">
++++

[.column]
.Magnolia Cloud

[.content]
A fully-managed database as a service designed to take the complexity out of deploying, managing, scaling, and securing Magnolia in the public cloud. With just a few clicks, you can store, query, and analyze any amount of data, all on the cloud service provider of your choice.
{empty}
* xref:cloud::index.adoc[Get Started with Magnolia Cloud]


[.column]
.Magnolia Autonomous Operator (Kubernetes)

[.content]
Native integration of Magnolia Server with open source Kubernetes and Red Hat OpenShift to automate the management of common Magnolia tasks such as the configuration, creation, scaling, and recovery of Magnolia clusters.
{empty}
* xref:operator::overview.adoc[Get Started with Autonomous Operator]

[.column]
.Magnolia Server

[.content]
An open source, distributed, JSON document database. It exposes a scale-out, key-value store with managed cache for sub-millisecond data operations, purpose-built indexers for efficient queries, and a powerful query engine for executing SQL-like queries.
{empty}
xref:server:getting-started:start-here.adoc[Get Started: Magnolia Server Enterprise]

[.column]
.Magnolia for Mobile/Edge

[.content]
Bring the power of NoSQL to the edge with Sync Gateway and Magnolia Lite. Combined with Magnolia Server, it provides fast, efficient bidirectional synchronization of data between the edge and the cloud. Enabling you to deploy your offline-first mobile and embedded applications with greater agility on premises or in any cloud.
{empty}
* xref:Magnolia-lite::introduction.adoc[Get Started with Magnolia Lite]
* xref:sync-gateway::index.adoc[Get Started with Sync Gateway]

++++
</div>
++++

== Quick Links
++++
<div class="card-row three-column-row">
++++

[.column]
.Learn More
* xref:tutorials::index.adoc[Explore the Tutorials]
* https://docs-archive.Magnolia.com[Documentation for Previous Versions]


[.column]
.Community Users
* xref:tutorials:getting-started-ce:index.adoc[Get Started: Magnolia Community Edition]
* https://forums.Magnolia.com[Engage with us on Magnolia Forums]

[.column]
.Feedback
* xref:server:introduction:contact-Magnolia.adoc[Contact Magnolia]
* xref:home:contribute:index.adoc[Contribute to the Documentation]


++++
</div>
++++